/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import Creation.CreationInterface;
import Login.LoginManager;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

public class GameDataForm extends javax.swing.JFrame {

    /**
     * Creates new form GameDataForm
     */
    public GameDataForm() {
        initComponents();
        Background.setSize(1366 , 768);
        this.setSize(1366 , 768);
        setDefaultCloseOperation(GameDataForm.EXIT_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Category = new javax.swing.ButtonGroup();
        Template = new javax.swing.ButtonGroup();
        homePage = new javax.swing.JToggleButton();
        Submit = new javax.swing.JToggleButton();
        Name = new javax.swing.JLabel();
        Subject = new javax.swing.JLabel();
        Number = new javax.swing.JLabel();
        GameCategory = new javax.swing.JLabel();
        Tips = new javax.swing.JLabel();
        GameType = new javax.swing.JLabel();
        gameNameField = new javax.swing.JTextField();
        QustionNumber = new javax.swing.JTextField();
        tipsField = new javax.swing.JTextField();
        Science = new javax.swing.JRadioButton();
        Math = new javax.swing.JRadioButton();
        Programming = new javax.swing.JRadioButton();
        MCQ = new javax.swing.JRadioButton();
        TF = new javax.swing.JRadioButton();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        homePage.setBackground(new java.awt.Color(0, 0, 0));
        homePage.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        homePage.setForeground(new java.awt.Color(255, 255, 255));
        homePage.setText("Home Page");
        homePage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homePageActionPerformed(evt);
            }
        });
        getContentPane().add(homePage);
        homePage.setBounds(583, 540, 200, 40);

        Submit.setBackground(new java.awt.Color(0, 0, 0));
        Submit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Submit.setForeground(new java.awt.Color(255, 255, 255));
        Submit.setText("Submit Data");
        Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitActionPerformed(evt);
            }
        });
        getContentPane().add(Submit);
        Submit.setBounds(583, 470, 200, 40);

        Name.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        Name.setForeground(new java.awt.Color(255, 255, 255));
        Name.setText("Game Name");
        Name.setName("Name"); // NOI18N
        getContentPane().add(Name);
        Name.setBounds(450, 110, 150, 50);

        Subject.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Subject.setForeground(new java.awt.Color(255, 255, 255));
        Subject.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Subject.setText("Game Data Form");
        Subject.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(Subject);
        Subject.setBounds(0, 50, 1366, 50);

        Number.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        Number.setForeground(new java.awt.Color(255, 255, 255));
        Number.setText("Questions Number");
        getContentPane().add(Number);
        Number.setBounds(450, 250, 150, 50);

        GameCategory.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        GameCategory.setForeground(new java.awt.Color(255, 255, 255));
        GameCategory.setText("Category Type");
        getContentPane().add(GameCategory);
        GameCategory.setBounds(450, 330, 150, 50);

        Tips.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        Tips.setForeground(new java.awt.Color(255, 255, 255));
        Tips.setText("Tips");
        getContentPane().add(Tips);
        Tips.setBounds(450, 180, 150, 50);

        GameType.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        GameType.setForeground(new java.awt.Color(255, 255, 255));
        GameType.setText("Qustion Type");
        getContentPane().add(GameType);
        GameType.setBounds(450, 400, 150, 50);

        gameNameField.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        gameNameField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        gameNameField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        gameNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gameNameFieldActionPerformed(evt);
            }
        });
        getContentPane().add(gameNameField);
        gameNameField.setBounds(700, 120, 300, 30);

        QustionNumber.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        QustionNumber.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        QustionNumber.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        QustionNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QustionNumberActionPerformed(evt);
            }
        });
        getContentPane().add(QustionNumber);
        QustionNumber.setBounds(700, 260, 300, 30);

        tipsField.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        tipsField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tipsField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        tipsField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipsFieldActionPerformed(evt);
            }
        });
        getContentPane().add(tipsField);
        tipsField.setBounds(700, 190, 300, 30);

        Science.setBackground(new java.awt.Color(0, 0, 0));
        Category.add(Science);
        Science.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        Science.setForeground(new java.awt.Color(255, 255, 255));
        Science.setText("Science");
        Science.setOpaque(false);
        Science.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ScienceActionPerformed(evt);
            }
        });
        getContentPane().add(Science);
        Science.setBounds(700, 330, 100, 50);

        Math.setBackground(new java.awt.Color(0, 0, 0));
        Category.add(Math);
        Math.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        Math.setForeground(new java.awt.Color(255, 255, 255));
        Math.setText("Math");
        Math.setOpaque(false);
        Math.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MathActionPerformed(evt);
            }
        });
        getContentPane().add(Math);
        Math.setBounds(800, 330, 100, 50);

        Programming.setBackground(new java.awt.Color(0, 0, 0));
        Category.add(Programming);
        Programming.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        Programming.setForeground(new java.awt.Color(255, 255, 255));
        Programming.setText("Programming");
        Programming.setOpaque(false);
        Programming.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProgrammingActionPerformed(evt);
            }
        });
        getContentPane().add(Programming);
        Programming.setBounds(900, 330, 150, 50);

        MCQ.setBackground(new java.awt.Color(0, 0, 0));
        Template.add(MCQ);
        MCQ.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        MCQ.setForeground(new java.awt.Color(255, 255, 255));
        MCQ.setText("MCQ");
        MCQ.setOpaque(false);
        MCQ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MCQActionPerformed(evt);
            }
        });
        getContentPane().add(MCQ);
        MCQ.setBounds(700, 400, 100, 50);

        TF.setBackground(new java.awt.Color(0, 0, 0));
        Template.add(TF);
        TF.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        TF.setForeground(new java.awt.Color(255, 255, 255));
        TF.setText("True & False");
        TF.setOpaque(false);
        TF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFActionPerformed(evt);
            }
        });
        getContentPane().add(TF);
        TF.setBounds(800, 400, 150, 50);

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Forms/The Brain.jpg"))); // NOI18N
        getContentPane().add(Background);
        Background.setBounds(0, 0, 950, 630);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void gameNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gameNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gameNameFieldActionPerformed

    private void homePageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homePageActionPerformed
        // TODO add your handling code here:
        HomePage HP = new HomePage();
        HP.setVisible(true);
        this.setVisible(false);
        LoginManager.user = null ;
    }//GEN-LAST:event_homePageActionPerformed

    private void MCQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MCQActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_MCQActionPerformed

    private void MathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MathActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_MathActionPerformed

    private void ProgrammingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProgrammingActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_ProgrammingActionPerformed

    private void TFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_TFActionPerformed

    private void ScienceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ScienceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ScienceActionPerformed

    private void QustionNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QustionNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_QustionNumberActionPerformed

    private void tipsFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipsFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipsFieldActionPerformed

    private void SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitActionPerformed
        
        this.setVisible(false);
        CreationInterface CI = new CreationInterface();
        String gameName = gameNameField.getText();
        String teacherName = LoginManager.user.getName();
        String teacherEmail = LoginManager.user.getEmail();
        String gameTips = tipsField.getText();
        String categoryType = null ;
        String gameType = null ;
        int numberofLevels = Integer.parseInt(QustionNumber.getText());
        if(Math.isSelected()) {
            categoryType = "Math";
        }
        else if(Science.isSelected()) {
            categoryType = "Science";
        }
        else if(Programming.isSelected()) {
            categoryType = "Programming";
        }
        if(MCQ.isSelected()) {
            gameType = "MCQ" ;
        }
        else if(TF.isSelected()) {
            gameType = "TF" ;
        }
        String Data = gameName + "," + teacherName + "," + teacherEmail + "," + gameType + "," +
        categoryType + "," + gameTips + "," + numberofLevels ;
        try {
            CI.sumbitGameData(Data);
        } catch (IOException ex) {
            Logger.getLogger(GameDataForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_SubmitActionPerformed

    /**
     * @param args the command line arguments
     */
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.ButtonGroup Category;
    private javax.swing.JLabel GameCategory;
    private javax.swing.JLabel GameType;
    private javax.swing.JRadioButton MCQ;
    private javax.swing.JRadioButton Math;
    private javax.swing.JLabel Name;
    private javax.swing.JLabel Number;
    private javax.swing.JRadioButton Programming;
    private javax.swing.JTextField QustionNumber;
    private javax.swing.JRadioButton Science;
    private javax.swing.JLabel Subject;
    private javax.swing.JToggleButton Submit;
    private javax.swing.JRadioButton TF;
    private javax.swing.ButtonGroup Template;
    private javax.swing.JLabel Tips;
    private javax.swing.JTextField gameNameField;
    private javax.swing.JToggleButton homePage;
    private javax.swing.JTextField tipsField;
    // End of variables declaration//GEN-END:variables
}
