package Forms;

import Login.LoginInterface;
import Login.LoginManager;
import java.awt.Color;
import java.awt.Desktop;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JEditorPane;

public class LoginForm extends javax.swing.JFrame {

    public static String Password;
    public static String Email;
    private static LoginInterface LI;

    public LoginForm() {
        initComponents();
        Submit.setBackground(Color.BLACK);
        Forget.setBackground(Color.BLACK);
        homePage.setBackground(Color.BLACK);
        Background.setSize(1366, 768);
        this.setSize(1366, 768);
        setDefaultCloseOperation(LoginForm.EXIT_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Subject = new javax.swing.JLabel();
        userPassword = new javax.swing.JLabel();
        EmailField = new javax.swing.JTextField();
        userEmail = new javax.swing.JLabel();
        Submit = new javax.swing.JToggleButton();
        Forget = new javax.swing.JToggleButton();
        homePage = new javax.swing.JToggleButton();
        passwordField = new javax.swing.JPasswordField();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                formComponentAdded(evt);
            }
        });
        getContentPane().setLayout(null);

        Subject.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Subject.setForeground(new java.awt.Color(255, 255, 255));
        Subject.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Subject.setText("Login Form");
        getContentPane().add(Subject);
        Subject.setBounds(0, 40, 1366, 50);

        userPassword.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        userPassword.setForeground(new java.awt.Color(255, 255, 255));
        userPassword.setText("Password");
        getContentPane().add(userPassword);
        userPassword.setBounds(450, 200, 150, 50);

        EmailField.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        EmailField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        EmailField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        EmailField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailFieldActionPerformed(evt);
            }
        });
        getContentPane().add(EmailField);
        EmailField.setBounds(700, 140, 300, 30);

        userEmail.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        userEmail.setForeground(new java.awt.Color(255, 255, 255));
        userEmail.setText("Email");
        getContentPane().add(userEmail);
        userEmail.setBounds(450, 140, 150, 50);

        Submit.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        Submit.setForeground(new java.awt.Color(255, 255, 255));
        Submit.setText("Login");
        Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitActionPerformed(evt);
            }
        });
        getContentPane().add(Submit);
        Submit.setBounds(583, 260, 200, 40);

        Forget.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        Forget.setForeground(new java.awt.Color(255, 255, 255));
        Forget.setText("Forget Password");
        Forget.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ForgetActionPerformed(evt);
            }
        });
        getContentPane().add(Forget);
        Forget.setBounds(583, 320, 200, 40);

        homePage.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        homePage.setForeground(new java.awt.Color(255, 255, 255));
        homePage.setText("Back");
        homePage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homePageActionPerformed(evt);
            }
        });
        getContentPane().add(homePage);
        homePage.setBounds(583, 380, 200, 40);

        passwordField.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        passwordField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        passwordField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(passwordField);
        passwordField.setBounds(700, 200, 300, 30);

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Forms/The Brain.jpg"))); // NOI18N
        getContentPane().add(Background);
        Background.setBounds(0, 0, 1366, 768);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EmailFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailFieldActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_EmailFieldActionPerformed

    private void SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitActionPerformed

        LI = new LoginInterface();
        try {
            Password = passwordField.getText();
            Email = EmailField.getText();
            LI.entersData(Email, Password);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.setVisible(false);
    }//GEN-LAST:event_SubmitActionPerformed

    private void ForgetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ForgetActionPerformed

        LI = new LoginInterface();
        Email = EmailField.getText();
        try {
            LI.recheckEmail(Email);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.setVisible(false);

    }//GEN-LAST:event_ForgetActionPerformed

    private void homePageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homePageActionPerformed
        // TODO add your handling code here:
        HomePage HP = new HomePage();
        HP.setVisible(true);
        this.setVisible(false);
        LoginManager.user = null;

    }//GEN-LAST:event_homePageActionPerformed

    private void formComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_formComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_formComponentAdded

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JTextField EmailField;
    private javax.swing.JToggleButton Forget;
    private javax.swing.JLabel Subject;
    private javax.swing.JToggleButton Submit;
    private javax.swing.JToggleButton homePage;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel userEmail;
    private javax.swing.JLabel userPassword;
    // End of variables declaration//GEN-END:variables
}
