
package Forms;

import Creation.CreationInterface;
import Login.LoginManager;
import Playing.PlayingInterface;
import java.awt.Color;
import java.io.FileNotFoundException;
import java.util.logging.Level;
import java.util.logging.Logger;

public class TeacherForm extends javax.swing.JFrame {

    public TeacherForm() {
        initComponents();
        Play.setBackground(Color.black);
        Create.setBackground(Color.black);
        gameState.setBackground(Color.black);
        Comments.setBackground(Color.black);
        homePage.setBackground(Color.black);
        Background.setSize(1366 , 768);
        this.setSize(1366 , 768);
        this.setDefaultCloseOperation(TeacherForm.EXIT_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Create = new javax.swing.JButton();
        Play = new javax.swing.JButton();
        gameState = new javax.swing.JButton();
        Comments = new javax.swing.JButton();
        homePage = new javax.swing.JToggleButton();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        Create.setBackground(new java.awt.Color(51, 51, 51));
        Create.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Create.setForeground(new java.awt.Color(255, 255, 255));
        Create.setText("Create");
        Create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateActionPerformed(evt);
            }
        });
        getContentPane().add(Create);
        Create.setBounds(583, 250, 200, 40);

        Play.setBackground(new java.awt.Color(51, 51, 51));
        Play.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Play.setForeground(new java.awt.Color(255, 255, 255));
        Play.setText("Play");
        Play.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlayActionPerformed(evt);
            }
        });
        getContentPane().add(Play);
        Play.setBounds(583, 200, 200, 40);

        gameState.setBackground(new java.awt.Color(51, 51, 51));
        gameState.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        gameState.setForeground(new java.awt.Color(255, 255, 255));
        gameState.setText("Games' State");
        gameState.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gameStateActionPerformed(evt);
            }
        });
        getContentPane().add(gameState);
        gameState.setBounds(583, 300, 200, 40);

        Comments.setBackground(new java.awt.Color(51, 51, 51));
        Comments.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Comments.setForeground(new java.awt.Color(255, 255, 255));
        Comments.setText("Games' Comments");
        Comments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CommentsActionPerformed(evt);
            }
        });
        getContentPane().add(Comments);
        Comments.setBounds(583, 350, 200, 40);

        homePage.setBackground(new java.awt.Color(51, 51, 51));
        homePage.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        homePage.setForeground(new java.awt.Color(255, 255, 255));
        homePage.setText("Home Page");
        homePage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homePageActionPerformed(evt);
            }
        });
        getContentPane().add(homePage);
        homePage.setBounds(583, 400, 200, 40);

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Forms/The Brain.jpg"))); // NOI18N
        getContentPane().add(Background);
        Background.setBounds(0, 0, 940, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateActionPerformed
        // TODO add your handling code here:
        GameDataForm Form = new GameDataForm();
        this.setVisible(false);
        Form.setVisible(true);
    }//GEN-LAST:event_CreateActionPerformed

    private void PlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlayActionPerformed
        CategoryListForm Form = new CategoryListForm();
        this.setVisible(false);
        Form.setVisible(true);
    }//GEN-LAST:event_PlayActionPerformed

    private void gameStateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gameStateActionPerformed
        // TODO add your handling code here:
        CreationInterface CI = new CreationInterface();
        try {
            CI.showGameState();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(TeacherForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_gameStateActionPerformed

    private void homePageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homePageActionPerformed
        // TODO add your handling code here:
        HomePage HP = new HomePage();
        HP.setVisible(true);
        this.setVisible(false);
        LoginManager.user = null ;

    }//GEN-LAST:event_homePageActionPerformed

    private void CommentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CommentsActionPerformed
        // TODO add your handling code here:
        PlayingInterface PI = new PlayingInterface();
        try {
            PI.showComments();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(TeacherForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_CommentsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JButton Comments;
    private javax.swing.JButton Create;
    private javax.swing.JButton Play;
    private javax.swing.JButton gameState;
    private javax.swing.JToggleButton homePage;
    // End of variables declaration//GEN-END:variables
}
