
package Forms;

import Creation.CreationInterface;
import Login.LoginManager;
import java.awt.Color;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

public class TFForm extends javax.swing.JFrame {

    
    public TFForm() {
        initComponents();
        Background.setSize(1366 , 768);
        this.setSize(1366 , 768);
        Submit.setSize(200, 40);
        Submit.setBackground(Color.black);
        Submit.setLocation(583, 200);
        homePage.setSize(200, 40);
        homePage.setBackground(Color.black);
        homePage.setLocation(583, 250);
        this.setDefaultCloseOperation(TFForm.EXIT_ON_CLOSE);
    }


    public String checkAnswer()
    {
        if(True.isSelected())
            return "True";
        else if(False.isSelected())
            return "False";
        
        return "";
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CorrctAnswer = new javax.swing.ButtonGroup();
        Subject = new javax.swing.JLabel();
        Question = new javax.swing.JLabel();
        QuestionField = new javax.swing.JTextField();
        Correct = new javax.swing.JLabel();
        True = new javax.swing.JRadioButton();
        False = new javax.swing.JRadioButton();
        homePage = new javax.swing.JToggleButton();
        Submit = new javax.swing.JToggleButton();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        Subject.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Subject.setForeground(new java.awt.Color(255, 255, 255));
        Subject.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Subject.setText("True & False Form");
        Subject.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(Subject);
        Subject.setBounds(0, 50, 1366, 50);
        Subject.getAccessibleContext().setAccessibleName("True & False");

        Question.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        Question.setForeground(new java.awt.Color(255, 255, 255));
        Question.setText("Question");
        getContentPane().add(Question);
        Question.setBounds(450, 100, 150, 30);

        QuestionField.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        QuestionField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        QuestionField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        QuestionField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuestionFieldActionPerformed(evt);
            }
        });
        getContentPane().add(QuestionField);
        QuestionField.setBounds(700, 100, 300, 30);

        Correct.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        Correct.setForeground(new java.awt.Color(255, 255, 255));
        Correct.setText("Correct Answer");
        getContentPane().add(Correct);
        Correct.setBounds(450, 150, 150, 30);

        True.setBackground(new java.awt.Color(0, 0, 0));
        CorrctAnswer.add(True);
        True.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        True.setForeground(new java.awt.Color(255, 255, 255));
        True.setText("True");
        True.setOpaque(false);
        True.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TrueActionPerformed(evt);
            }
        });
        getContentPane().add(True);
        True.setBounds(800, 150, 100, 30);

        False.setBackground(new java.awt.Color(0, 0, 0));
        CorrctAnswer.add(False);
        False.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        False.setForeground(new java.awt.Color(255, 255, 255));
        False.setText("False");
        False.setActionCommand("True");
        False.setOpaque(false);
        False.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FalseActionPerformed(evt);
            }
        });
        getContentPane().add(False);
        False.setBounds(700, 150, 100, 30);

        homePage.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        homePage.setForeground(new java.awt.Color(255, 255, 255));
        homePage.setText("Home Page");
        homePage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homePageActionPerformed(evt);
            }
        });
        getContentPane().add(homePage);
        homePage.setBounds(583, 250, 200, 40);

        Submit.setBackground(new java.awt.Color(0, 0, 0));
        Submit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Submit.setForeground(new java.awt.Color(255, 255, 255));
        Submit.setText("Submit Data");
        Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitActionPerformed(evt);
            }
        });
        getContentPane().add(Submit);
        Submit.setBounds(583, 200, 200, 31);

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Forms/The Brain.jpg"))); // NOI18N
        getContentPane().add(Background);
        Background.setBounds(0, 0, 1365, 768);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitActionPerformed
        
        String level = QuestionField.getText() + ",";
        if(True.isSelected()) {
            level += "True" ;
        }
        else if(False.isSelected()) {
            level += "False" ;
        }
        this.setVisible(false);
        try {
            CreationInterface.addLevel(level);
        } catch (IOException ex) {
            Logger.getLogger(TFForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
    }//GEN-LAST:event_SubmitActionPerformed

    private void homePageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homePageActionPerformed
        // TODO add your handling code here:
        HomePage HP = new HomePage();
        HP.setVisible(true);
        this.setVisible(false);
        LoginManager.user = null ;

    }//GEN-LAST:event_homePageActionPerformed

    private void QuestionFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuestionFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_QuestionFieldActionPerformed

    private void FalseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FalseActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_FalseActionPerformed

    private void TrueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TrueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TrueActionPerformed

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.ButtonGroup CorrctAnswer;
    private javax.swing.JLabel Correct;
    private javax.swing.JRadioButton False;
    private javax.swing.JLabel Question;
    private javax.swing.JTextField QuestionField;
    private javax.swing.JLabel Subject;
    private javax.swing.JToggleButton Submit;
    private javax.swing.JRadioButton True;
    private javax.swing.JToggleButton homePage;
    // End of variables declaration//GEN-END:variables
}
